---
output: github_document
---

# TeslaInvestR

## Overview

**TeslaInvestR** is an R package that provides historical Tesla stock price data and Tesla Roadster depreciation data. The package allows users to compare Tesla stock investment growth with the depreciation of Tesla Roadsters over time. It also includes functions to visualize these comparisons using `ggplot2` and an interactive Shiny app.

## Features

- **Tesla Stock Data**: Historical data on Tesla stock prices from 2011 to 2023, including adjusted close prices and calculated investment values based on an initial investment.
- **Tesla Roadster Depreciation Data**: Yearly depreciation values for Tesla Roadsters from 2010 to 2024.
- **Interactive Shiny App**: An interactive Shiny app for comparing Tesla stock performance and Tesla Roadster depreciation.

## Installation

You can install the **TeslaInvestR** package from GitHub using the following command:

```{r eval=FALSE}
# Install TeslaInvestR from GitHub
remotes::install_github("nnam0004/TeslaInvestR")
```


## Usage




## Data Sources

- **Tesla Stock Data**: Data sourced from Yahoo Finance, covering the period from 2011 to 2023.
- **Tesla Roadster Depreciation Data**: Simulated data representing the yearly depreciation of the Tesla Roadster from 2010 to 2024.

## License

This package is licensed under the MIT License. See the `LICENSE` file for more information.

## Contributions

Contributions are welcome! Feel free to submit pull requests or report issues on GitHub.


